//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Folio1_App_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Classes
    {
        public tbl_Classes()
        {
            this.tbl_Students = new HashSet<tbl_Students>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string TeacherName { get; set; }
    
        public virtual ICollection<tbl_Students> tbl_Students { get; set; }
    }
}
